const { Router } = require('express');
const c = require('./dashboard.controller');
const { authenticate } = require('../../middleware/auth');
const router = Router();
router.use(authenticate);
router.get('/',                c.getDashboard);
router.get('/by-category',     c.getAssetsByCategory);
router.get('/by-status',       c.getAssetsByStatus);
router.get('/maintenance-trend', c.getMaintenanceTrend);
module.exports = router;
